CREATE TABLE logs (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    latitude NUMERIC NOT NULL,
    longitude NUMERIC NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    image TEXT,
    rating INTEGER NOT NULL,
    visitedDay TIMESTAMP,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);