CREATE TABLE logs (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    latitude NUMERIC(10,8) NOT NULL,
    longitude NUMERIC(10,8) NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    image TEXT,
    rating INTEGER NOT NULL,
    visited_day TIMESTAMP NOT NULL,
    public BOOLEAN DEFAULT FALSE,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);